name = "entsoe_api"
uuid = "185eae8d-c2be-406a-8f52-658f6fb4423d"
authors = ["Su-"]
version = "0.1.0"

[compat]
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
